color0 #0f141c
color1 #ffb4ab
color2 #a7c8ff
color3 #82d3e1
color4 #50d8ed
color5 #a7c8ff
color6 #82d3e1
color7 #dee2ef
color8 #8791a5
color9 #ffb4ab
color10 #a7c8ff
color11 #82d3e1
color12 #50d8ed
color13 #a7c8ff
color14 #82d3e1
color15 #dee2ef

cursor                #dee2ef
cursor_text_color     #0f141c
background            #0f141c
foreground            #dee2ef
selection_foreground  #bdc7dc
selection_background  #3d4758
url_color             #50d8ed